version: '3.1'
services:
  db:
    image: 'postgres:10-alpine'
    environment:
      POSTGRES_USER: kaleido
      POSTGRES_PASSWORD: !SECRET!
    restart: always
    expose:
    - "5432"

  master:
    image: 'longfangsong/kaleido-master:0.0.4'
    environment:
      CONNSTR: 'host=db port=5432 user=kaleido password=!SECRET! dbname=kaleido sslmode=disable'
      OSS_END_POINT: oss-cn-hangzhou.aliyuncs.com
      OSS_ACCESS_KEY: LTAIhRAdblzkbQPm
      OSS_ACCESS_SECRET: !SECRET!
    restart: always
    ports:
    - "8086:8086"

  node:
    image: 'longfangsong/kaleido-node:0.0.5'
    environment:
      OSS_END_POINT: oss-cn-hangzhou.aliyuncs.com
      OSS_ACCESS_KEY: LTAIhRAdblzkbQPm
      OSS_ACCESS_SECRET: !SECRET!
    restart: always
    network_mode: 'host'

  frontend:
    image: 'longfangsong/kaleido-frontend'
    restart: always
    expose:
    - "80"
