version: '3'
services:
  db:
    image: 'postgres:10-alpine'
    environment:
      POSTGRES_USER: 'kaleido'
      POSTGRES_PASSWORD: CHANGEWHENDEPLOY
    restart: always

  master:
    image: 'longfangsong/kaleido-master:0.1.0'
    environment:
      CONNSTR: 'postgres://kaleido:kaleido@db/kaleido?sslmode=disable'
      OSS_END_POINT: 'oss-cn-hangzhou.aliyuncs.com'
      OSS_ACCESS_KEY: 'LTAIhRAdblzkbQPm'
      OSS_ACCESS_SECRET: CHANGEWHENDEPLOY
    restart: always
    ports:
    - "8086:8086"

  node:
    image: 'longfangsong/kaleido-node:0.1.0'
    environment:
      OSS_END_POINT: 'oss-cn-hangzhou.aliyuncs.com'
      OSS_ACCESS_KEY: 'LTAIhRAdblzkbQPm'
      OSS_ACCESS_SECRET: CHANGEWHENDEPLOY
    restart: always
    network_mode: 'host'

  frontend:
    image: 'longfangsong/kaleido-frontend:0.1.8'
    restart: always
    ports:
    - "80:80"