version: '3'
services:
  db:
    image: 'postgres:10-alpine'
    environment:
    - POSTGRES_USER: kaleido
    - POSTGRES_PASSWORD: !CHANGE_THIS_WHEN_DEPLOY!
    restart: always

  master:
    image: 'longfangsong/kaleido-master:0.0.4'
    environment:
    - CONNSTR: 'postgres://kaleido:!CHANGE_THIS_WHEN_DEPLOY!@db/kaleido?sslmode=disable'
    - OSS_END_POINT: oss-cn-hangzhou.aliyuncs.com
    - OSS_ACCESS_KEY: LTAIhRAdblzkbQPm
    - OSS_ACCESS_SECRET: !CHANGE_THIS_WHEN_DEPLOY!
    restart: always
    ports:
    - "8086:8086"

  node:
    image: 'longfangsong/kaleido-node:0.0.5'
    environment:
    - OSS_END_POINT: oss-cn-hangzhou.aliyuncs.com
    - OSS_ACCESS_KEY: LTAIhRAdblzkbQPm
    - OSS_ACCESS_SECRET: !CHANGE_THIS_WHEN_DEPLOY!
    restart: always
    network_mode: 'host'

  frontend:
    image: 'longfangsong/kaleido-frontend'
    restart: always
    ports:
    - "80:8080"
